services:
  finance-app:
    build: .
    container_name: MadFinance
    ports:
      - "5001:5000"
    volumes:
      - ./app/data:/app/app/data  # This saves your finance.db file on your Unraid drive
    restart: unless-stopped